package br.cti.dt3d.genericos;

import java.util.ArrayList;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.text.Editable;
import android.text.TextWatcher;
import android.util.Log;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.view.inputmethod.InputMethodManager;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ArrayAdapter;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;

public class SubstanciasActivity extends Activity implements OnItemClickListener {
	
	static ListView lv1;
	static EditText et1;
	
	ArrayAdapter<String> aa;
		
	static String[] array = {"abatacepte",
			"abciximabe",
			"acarbose",
			"acebrofilina",
			"aceclofenaco",
			"aceponato de metilprednisolona",
			"acetato de busserrelina",
			"acetato de caspofungina",
			"acetato de cetrorrelix",
			"acetato de ciproterona",
			"acetato de ciproterona, etinilestradiol",
			"acetato de ciproterona, valerato de estradiol",
			"acetato de clormadinona, etinilestradiol",
			"Acetato de Degarelix",
			"acetato de desmopressina",
			"acetato de dexametasona",
			"acetato de dexametasona, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina",
			"acetato de dexametasona, clotrimazol",
			"acetato de dexametasona, fosfato dissódico de dexametasona",
			"acetato de dextroalfatocoferol",
			"acetato de fludrocortisona",
			"acetato de fluormetolona",
			"acetato de ganirrelix",
			"acetato de glatirâmer",
			"acetato de gosserrelina",
			"acetato de hidrocortisona",
			"acetato de hidroxocobalamina, uridina, citidina",
			"Acetato de Icatibanto",
			"acetato de lanreotida",
			"acetato de leuprorrelina",
			"acetato de medroxiprogesterona",
			"acetato de medroxiprogesterona, valerato de estradiol",
			"acetato de megestrol",
			"acetato de metilprednisolona",
			"acetato de nafarrelina",
			"acetato de nomegestrol",
			"acetato de noretisterona",
			"acetato de noretisterona, etinilestradiol",
			"acetato de octreotida",
			"acetato de potássio, acetato de sódio, acetato de magnésio, prolina, cloridrato de ornitina, glicose, cloridrato de cisteína, acetiltirosina, glicina, alanina, serina, ácido aspártico, ácido glutâmico, tirosina, leucina, metionina, fenilalanina, ácido mál",
			"acetato de potássio, acetato de sódio, prolina, glicose, glicina, alanina, serina, glicerol, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, levovalina, treonina, triptofana, isoleucina, arginina, cloreto de sódio",
			"acetato de prednisolona",
			"acetato de prednisona, rifamicina",
			"acetato de racealfatocoferol",
			"acetato de retinol",
			"acetato de retinol, cloranfenicol, metionina",
			"acetato de retinol, cloridrato de piridoxina, acetato de dextroalfatocoferol",
			"acetato de retinol, cloridrato de piridoxina, colecalciferol",
			"acetato de retinol, cloridrato de tiamina, colecalciferol, citrato de cálcio, riboflavina",
			"acetato de retinol, colecalciferol",
			"acetato de retinol, selenato de sódio, pantotenato de cálcio, fumarato ferroso, ácido ascórbico, nitrato de tiamina, adenosina, biotina, ácido fólico, cianocobalamina, betacaroteno, acetato de racealfatocoferol, riboflavina, inositol, nicotinamida",
			"acetato de sódio triidratado",
			"acetato de triptorrelina",
			"acetazolamida",
			"acetilcisteína",
			"acetilcisteína, acetilcisteína",
			"acetilcisteína, sulfato de tuaminoeptano",
			"acetilmetionina",
			"aciclovir",
			"aciclovir sódico",
			"ácido acetilsalicílico",
			"ácido acetilsalicílico, ácido ascórbico",
			"ácido acetilsalicílico, cafeína",
			"ácido acetilsalicílico, dipropionato de betametasona",
			"ácido acetilsalicílico, enxofre",
			"ácido acetilsalicílico, sinvastatina",
			"ácido aminocapróico",
			"ácido ascórbico",
			"ácido ascórbico, ácido fólico",
			"ácido ascórbico, aspartato de arginina",
			"ácido ascórbico, cafeína, dipirona sódica, guaifenesina",
			"ácido ascórbico, cafeína, maleato de mepiramina, dipirona sódica",
			"ácido ascórbico, citrato de zinco",
			"ácido ascórbico, cloridrato de piridoxina, biotina, acetato de dextroalfatocoferol, ácido fólico, cloridrato de tiamina, colecalciferol, cianocobalamina, palmitato de retinol, dexpantenol, riboflavina, fitomenadiona, nicotinamida",
			"ácido ascórbico, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina, cloridrato de ciproeptadina, nicotinamida",
			"ácido ascórbico, cloridrato de piridoxina, cloridrato de tiamina, riboflavina, cloridrato de ciproeptadina, nicotinamida",
			"ácido ascórbico, dipirona sódica",
			"ácido ascórbico, dipirona sódica monoidratada, guaiacol, guaifenesina",
			"ácido ascórbico, frutose, cloridrato de piridoxina, cianocobalamina, riboflavina, nicotinamida",
			"ácido ascórbico, frutose, cloridrato de piridoxina, riboflavina, nicotinamida",
			"ácido ascórbico, tiamina, cianocobalamina, sulfato ferroso, ácido pantotênico, riboflavina, nicotinamida",
			"ácido ascórbico, tiamina, piridoxina",
			"ácido ascórbico, tiamina, piridoxina, cianocobalamina, riboflavina, cloridrato de ciproeptadina, nicotinamida",
			"ácido azeláico",
			"ácido benzóico, ácido salicílico, iodo",
			"ácido benzóico, ácido salicílico, iodo, iodeto de sódio",
			"ácido benzóico, iodeto de potássio",
			"ácido benzóico, iodo",
			"ácido bórico, borato de sódio, cloridrato de nafazolina, sulfato de zinco",
			"ácido bórico, cloreto de benzalcônio",
			"ácido bórico, cloridrato de nafazolina, sulfato de zinco",
			"ácido bórico, clorobutanol, cloreto de sódio",
			"ácido bórico, fucsina básica, ácido salicílico, iodo, iodeto de potássio",
			"ácido bórico, óxido de zinco, metabissulfito de sódio, nafazolina",
			"ácido bórico, propionato de sódio, nistatina, tirotricina, sulfato de neomicina, fosfato dissódico de dexametasona",
			"ácido bórico, tirotricina, procaína, ácido salicílico",
			"ácido fólico",
			"ácido fólico, cianocobalamina, sulfato ferroso",
			"ácido fólico, ferripolimaltose",
			"ácido fólico, ferrro aminoacido quelato",
			"ácido folínico",
			"ácido fosfórico, sulfato ferroso",
			"ácido fosfórico, sulfato ferroso heptaidratado",
			"ácido fosfórico, sulfato ferroso, NC/NI",
			"ácido fusídico",
			"ácido gadotérico",
			"ácido gamaminobutírico",
			"ácido glutâmico, acetato de dextroalfatocoferol, tiamina, cloridrato de ioimbina, piridoxina, riboflavina",
			"ácido hialurônico",
			"ácido ibandrônico",
			"ácido ioxáglico, meglumina",
			"ácido ioxitalâmico, meglumina",
			"ácido isospaglúmico",
			"ácido láctico, ácido salicílico",
			"ácido mefenâmico",
			"ácido nalidíxico",
			"ácido nicotínico",
			"ácido pipemídico",
			"ácido poliacrílico",
			"ácido salicílico",
			"ácido salicílico, enxofre",
			"ácido salicílico, iodo",
			"ácido tióctico",
			"ácido tranexâmico",
			"ácido undecilênico, hexilresorcinol, propionato de cálcio, undecilenato de zinco",
			"ácido undecilênico, hexilresorcinol, propionato de sódio, ácido propiônico",
			"ácido ursodesoxicólico",
			"ácido valpróico",
			"ácido zoledrônico",
			"acitretina",
			"adalimumabe",
			"adapaleno",
			"adapaleno, clindamicina",
			"adapaleno, fosfato de clindamicina",
			"adapaleno, peróxido de benzoíla",
			"adefovir dipivoxila",
			"adenosina",
			"agomelatina",
			"água",
			"água para injeção",
			"alanilglutamina",
			"albendazol",
			"albumina humana",
			"alcatrão mineral",
			"álcool polivinílico",
			"álcool polivinílico, povidona",
			"aldesleucina",
			"alendronato de sódio",
			"alendronato de sódio, carbonato de cálcio, colecalciferol",
			"alendronato de sódio, colecalciferol",
			"alentuzumabe",
			"alfa1antitripsina",
			"alfacalcidol",
			"alfacorifolitropina",
			"alfacoriogonadotropina",
			"alfadornase",
			"alfadrotrecogina",
			"alfaepoetina",
			"alfaeptacogue ativado",
			"alfaestradiol",
			"alfafolitropina",
			"alfagalsidase",
			"alfainterferona 2a",
			"alfainterferona 2b",
			"Alfalglicosidase",
			"alfalutropina",
			"alfalutropina, alfafolitropina",
			"alfamilase bacteriana, quimotripsina, mucopolissacaridase",
			"alfapeginterferona 2a",
			"alfapeginterferona 2a, ribavirina",
			"alfapeginterferona 2b",
			"alfatirotropina",
			"algestona acetofenida, enantato de estradiol",
			"alisquireno",
			"alisquireno, anlodipino",
			"alisquireno, hidroclorotiazida",
			"aloína",
			"aloína, cloreto de metiltionínio, teobromina",
			"alopurinol",
			"alprazolam",
			"alprostadil",
			"alteplase",
			"ambrisentana",
			"ambroxol",
			"amicacina",
			"amifostina",
			"amilopectina",
			"aminaftona",
			"aminofilina",
			"amiodarona",
			"amissulprida",
			"amitriptilina",
			"amoxicilina",
			"amoxicilina sódica, clavulanato de potássio",
			"amoxicilina sódica, sulbactam sódica",
			"amoxicilina triidratada",
			"amoxicilina triidratada, sulbactam",
			"amoxicilina, ácido clavulânico",
			"amoxicilina, clavulanato de potássio",
			"amoxicilina, omeprazol, claritromicina",
			"amoxicilina, sulbactam",
			"ampicilina",
			"ampicilina benzatina, ampicilina sódica",
			"ampicilina sódica",
			"ampicilina triidratada",
			"amprenavir",
			"anastrozol",
			"anastrozol, lactose",
			"anfepramona",
			"anfotericina B",
			"anfotericina B, cloridrato de tetraciclina",
			"anfotericina B, tetraciclina",
			"anidulafungina",
			"antimoniato de meglumina",
			"antitrombina III",
			"Apixabana",
			"aprepitanto",
			"aprotinina",
			"argipressina",
			"aripiprazol",
			"ascorbato de sódio, pantotenato de cálcio, cloridrato de piridoxina, tiamina, cianocobalamina, riboflavina, nicotinamida",
			"asparaginase",
			"aspartato de arginina",
			"aspartato de magnésio, aspartato de potássio, cloridrato de piridoxina, cloridrato de tiamina, riboflavina",
			"aspartato de ornitina",
			"atenolol",
			"atenolol, clortalidona",
			"atorvastatina cálcica",
			"atosibana",
			"atropina",
			"axetilcefuroxima",
			"azacitidina",
			"azatioprina",
			"azitromicina",
			"azitromicina diidratada",
			"aztreonam",
			"bacitracina",
			"baclofeno",
			"basiliximabe",
			"benfotiamina",
			"benzbromarona",
			"benzidamina",
			"benzilpenicilina",
			"benzilpenicilina benzatina",
			"benzilpenicilina potássica",
			"benzilpenicilina potássica, benzilpenicilina procaína",
			"benzilpenicilina procaína",
			"benznidazol",
			"benzoato de benzila",
			"benzoato de benzila, ácido esteárico",
			"benzoato de benzila, óxido de zinco, acetato de hidrocortisona, subgalato de bismuto",
			"benzoato de betametasona",
			"benzoato de estradiol",
			"benzoato de rizatriptana",
			"benzoato de sódio",
			"benzocaína",
			"benzoilmetronidazol",
			"benzoilmetronidazol, nistatina",
			"benzoilmetronidazol, nistatina, cloreto de benzalcônio",
			"beractanto",
			"besilato de anlodipino",
			"besilato de anlodipino, atenolol",
			"besilato de anlodipino, atorvastatina cálcica",
			"besilato de anlodipino, cloridrato de benazepril",
			"besilato de anlodipino, losartana potássica",
			"besilato de anlodipino, maleato de enalapril",
			"besilato de anlodipino, olmesartana medoxomila",
			"besilato de anlodipino, ramipril",
			"besilato de anlodipino, telmisartana",
			"besilato de anlodipino, valsartana",
			"besilato de anlodipino, valsartana, hidroclorotiazida",
			"besilato de atracúrio",
			"besilato de cisatracúrio",
			"betaepoetina",
			"Betaepoetina-metoxipolietilenoglicol",
			"betafolitropina",
			"betagalsidase",
			"betaglucana",
			"betaína, acetilmetionina, citrato de colina",
			"betaína, cianocobalamina, citrato de colina",
			"betaína, cloridrato de piridoxina, adenosina, metionina, citrato de colina",
			"betaína, cloridrato de piridoxina, tiamina, acetilmetionina, cloreto de colina, riboflavina",
			"betaína, metionina, citrato de colina",
			"betaína, sorbitol, adenosina, metionina, piridoxina",
			"betaína, sorbitol, cloridrato de piridoxina, adenosina, citrato de colina",
			"betaína, sorbitol, metionina, citrato de colina",
			"betainterferona 1a",
			"betainterferona 1b",
			"betaistina",
			"betameprodina",
			"betametasona",
			"betametasona, cetoconazol",
			"bevacizumabe",
			"bezafibrato",
			"bicalutamida",
			"bicarbonato de sódio",
			"bicarbonato de sódio, ácido acetilsalicílico, ácido cítrico",
			"bicarbonato de sódio, carbonato de cálcio, Alginato de Sódio",
			"bicarbonato de sódio, carbonato de cálcio, carbonato de magnésio, carbonato básico de bismuto",
			"bicarbonato de sódio, carbonato de cálcio, carbonato de magnésio, carbonato básico de bismuto, NC/NI",
			"bicarbonato de sódio, carbonato de cálcio, carbonato de magnésio, NC/NI",
			"bicarbonato de sódio, carbonato de sódio, ácido acetilsalicílico, ácido cítrico",
			"bicarbonato de sódio, carbonato de sódio, ácido cítrico",
			"bicarbonato de sódio, clorato de potássio, benzocaína",
			"bicarbonato de sódio, glicose, cloreto de sódio",
			"bicarbonato de sódio, sulfato de magnésio",
			"bifonazol",
			"bimatoprosta",
			"bimatoprosta, maleato de timolol",
			"biperideno",
			"bisacodil",
			"bisoprolol",
			"bissulfato de clopidogrel",
			"bissulfato de clopidogrel, ácido acetilsalicílico",
			"borato de sódio, bicarbonato de sódio, clorato de potássio, benzocaína",
			"borato de sódio, cloridrato de nafazolina, sulfato de zinco",
			"bortezomibe",
			"bosentana",
			"brinzolamida",
			"brinzolamida, maleato de timolol",
			"bromazepam",
			"bromazina",
			"brometo de ipratrópio",
			"brometo de ipratrópio, sulfato de salbutamol",
			"Brometo de metilnatrexona",
			"brometo de otilônio",
			"brometo de pancurônio",
			"brometo de pinavério",
			"brometo de piridostigmina",
			"brometo de rocurônio",
			"brometo de tiotrópio",
			"brometo de vecurônio",
			"bromidrato de citalopram",
			"bromidrato de dextrometorfano",
			"bromidrato de dextrometorfano, guaifenesina",
			"bromidrato de fenoterol",
			"bromidrato de fenoterol, brometo de ipratrópio",
			"bromoprida",
			"bromoprida, pancreatina, dimeticona",
			"budesonida",
			"bumetanida",
			"buprenorfina",
			"bupropiona",
			"bussulfano",
			"butilbrometo de escopolamina",
			"butilbrometo de escopolamina, bromidrato de hiosciamina, dipirona sódica, metilbrometo de homatropina",
			"butilbrometo de escopolamina, dipirona sódica",
			"butilbrometo de escopolamina, dipirona sódica monoidratada",
			"butirato de hidrocortisona",
			"cabazitaxel",
			"cabergolina",
			"cafeína, cloridrato de isometepteno, dipirona sódica",
			"cafeína, cloridrato de piridoxina, nicotinamida",
			"cafeína, dipirona sódica",
			"cafeína, dipirona sódica monoidratada, orfenadrina",
			"cafeína, dipirona sódica, mucato de isometepteno",
			"cafeína, dipirona sódica, orfenadrina",
			"cafeína, mesilato de diidroergotamina, dipirona sódica",
			"calamina",
			"calcipotriol",
			"calcipotriol, dipropionato de betametasona",
			"calcitonina sintética de salmão",
			"calcitriol",
			"calcitriol, ácido ascórbico, dextroalfatocoferol, tiamina, cianocobalamina, retinol, iodo, sulfato de manganês, riboflavina, nicotinamida",
			"cambendazol",
			"cambendazol, mebendazol",
			"canaquinumabe",
			"candesartana",
			"candesartana cilexetila",
			"candesartana, felodipino",
			"cânfora, mentol",
			"cânfora, mentol, timol",
			"capecitabina",
			"caproato de hidroxiprogesterona, valerato de estradiol",
			"capsaicina",
			"captopril",
			"carbacol",
			"carbamazepina",
			"carbazocromo",
			"carbetocina",
			"carbidopa, levodopa",
			"carbocisteína",
			"carbômer 980, sorbitol",
			"carbonato de cálcio",
			"carbonato de cálcio, ácido ascórbico",
			"carbonato de cálcio, ácido ascórbico, cloridrato de piridoxina, colecalciferol",
			"carbonato de cálcio, ácido ascórbico, piridoxina, cianocobalamina",
			"carbonato de cálcio, colecalciferol",
			"carbonato de cálcio, dextroalfatocoferol, nicotinamida",
			"carbonato de cálcio, lactobionato de cálcio, ácido ascórbico",
			"carbonato de cálcio, lactogliconato de cálcio",
			"carbonato de lantanio octaidratado",
			"carbonato de lítio",
			"Carbonato de lodenafila",
			"Carbonato de Sevelâmer",
			"carboplatina",
			"carmelose",
			"carmelose sódica",
			"carmelose sódica, metilcelulose",
			"carmustina",
			"carnitina, ácido gamaminobutírico, lisina, cloridrato de piridoxina, tiamina, cianocobalamina, buclizina, riboflavina, nicotinamida",
			"carvedilol",
			"cefaclor",
			"cefaclor monoidratado",
			"cefadroxila",
			"cefalexina",
			"cefalexina monoidratada",
			"cefalotina",
			"cefalotina sódica",
			"cefazolina sódica",
			"cefepima",
			"cefotaxima",
			"cefotaxima sódica",
			"cefoxitina",
			"cefoxitina sódica",
			"cefprozila",
			"ceftazidima",
			"ceftazidima pentaidratada",
			"ceftazidima sódica",
			"ceftriaxona",
			"ceftriaxona dissódica hemieptaidratada",
			"ceftriaxona sódica",
			"cefuroxima",
			"cefuroxima sódica",
			"celecoxibe",
			"Certolizumabe Pegol",
			"cetoconazol",
			"cetoprofeno",
			"cetorolaco, trometamol",
			"cetotifeno",
			"cetrimida",
			"cetuximabe",
			"cianocobalamina",
			"cianocobalamina (58Co), colecalciferol, fluoreto de sódio",
			"cianocobalamina, riboflavina",
			"cianocobalamina, sulfato de zinco, fosfato de cálcio dibásico, lactato de cálcio",
			"ciclamato de sódio, sorbitol, propilparabeno, metilparabeno",
			"ciclesonida",
			"ciclobenzaprina",
			"ciclobenzaprina, cafeína",
			"ciclofenila",
			"ciclofosfamida",
			"ciclofosfamida monoidratada",
			"ciclopirox",
			"ciclopirox olamina",
			"ciclosporina",
			"cilazapril",
			"cilostazol",
			"cimetidina",
			"cinarizina",
			"cipionato de estradiol, acetato de medroxiprogesterona",
			"cipionato de testosterona",
			"cipionato de testosterona, acetato de medroxiprogesterona",
			"ciproeptadina",
			"ciproeptadina, ácido ascórbico, propilenoglicol, tiamina, piridoxina, riboflavina, nicotinamida",
			"ciprofibrato",
			"ciprofloxacino",
			"ciprofloxacino, cloridrato de ciprofloxacino",
			"ciproterona",
			"ciproterona, etinilestradiol",
			"cisplatina",
			"citalopram",
			"citarabina",
			"citicolina sódica",
			"citrato de cálcio",
			"citrato de clomifeno",
			"citrato de daunorrubicina",
			"citrato de feniltoloxamina, cloridrato de fenilpropanolamina, maleato de carbinoxamina, cloridrato de fenilefrina",
			"citrato de fentanila",
			"citrato de magnésio, glicose, citrato de sódio, cloreto de potássio, fosfato de sódio monobásico, cloreto de sódio, ácido cítrico, lactato de cálcio",
			"citrato de orfenadrina, cafeína, dipirona sódica",
			"citrato de orfenadrina, cafeína, dipirona sódica monoidratada",
			"citrato de potássio",
			"citrato de sildenafila",
			"citrato de sódio, cloreto de potássio, cloreto de sódio",
			"citrato de sufentanila",
			"citrato de tamoxifeno",
			"citrato férrico amoniacal",
			"cladribina",
			"claritromicina",
			"clavulanato de potássio",
			"clavulanato de potássio, amoxicilina triidratada",
			"clindamicina",
			"clindamicina, peróxido de benzoíla",
			"clioquinol, fludroxicortida",
			"clioquinol, gentamicina, valerato de betametasona, tolnaftato",
			"clioquinol, hidrocortisona",
			"clioquinol, pivalato de flumetasona",
			"clioquinol, sulfato de gentamicina, valerato de betametasona, tolnaftato",
			"clioquinol, sulfato de neomicina, valerato de betametasona, tolnaftato",
			"clioquinol, sulfato de polimixina B, prednisona, benzocaína",
			"clioquinol, valerato de betametasona",
			"clobazam",
			"clodronato dissódico",
			"clofibrato de etofilina, tartarato de nicotinila",
			"clonazepam",
			"clonixinato de lisina",
			"clopidogrel",
			"clorambucila",
			"cloranfenicol",
			"cloranfenicol, cloridrato de lidocaína",
			"cloranfenicol, colagenase",
			"cloranfenicol, fibrinolisina",
			"clordiazepóxido",
			"cloreto crômico hexaidratado, sulfato de zinco heptaidratado, sulfato cúprico pentaidratado, sulfato de manganês monoidratado",
			"cloreto de amônio, benzoato de sódio, ácido aminocapróico, guaifenesina",
			"cloreto de amônio, citrato de sódio",
			"cloreto de amônio, cloridrato de difenidramina",
			"cloreto de amônio, cloridrato de difenidramina, citrato de sódio",
			"cloreto de amônio, cloridrato de difenidramina, citrato de sódio, mentol",
			"cloreto de amônio, sulfoguaiacol, cloridrato de difenidramina, citrato de sódio",
			"cloreto de benzalcônio",
			"cloreto de benzalcônio, benzocaína",
			"cloreto de benzetônio",
			"cloreto de benzetônio, benzoxiquina, mentol",
			"cloreto de benzetônio, benzoxiquina, mentol, benzocaína",
			"cloreto de benzetônio, cloridrato de lidocaína",
			"cloreto de benzetônio, lidocaína",
			"cloreto de benzetônio, sulfato de neomicina, ergocalciferol, retinol",
			"cloreto de benzoxônio, cloreto de sódio",
			"cloreto de betanecol",
			"cloreto de cálcio",
			"cloreto de cálcio diidratado, acetato de potássio, acetato de sódio, acetato de magnésio, prolina, glicose, glicina, alanina, serina, glicerol, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, cloridrato de lisina, levovalina, treonina,",
			"cloreto de cálcio diidratado, acetato de potássio, acetato de sódio, hidróxido de sódio, acetato de magnésio, prolina, glicose, glicina, alanina, serina, glicerol, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, cloridrato de histidina",
			"cloreto de cálcio diidratado, acetato de potássio, acetato de sódio, hidróxido de sódio, acetato de magnésio, prolina, glicose, glicina, alanina, serina, glicerol, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, cloridrato de lisina, l",
			"cloreto de cálcio diidratado, acetato de potássio, acetato de sódio, prolina, glicose, glicina, alanina, serina, glicerol, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, cloridrato de lisina, levovalina, treonina, triptofana, isoleuci",
			"cloreto de cálcio diidratado, acetato de sódio triidratado, ácido málico, cloreto de potássio, cloreto de sódio, cloreto de magnésio hexaidratado, hetamido",
			"cloreto de cálcio diidratado, acetato de sódio, citrato de sódio, cloreto de potássio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, acetato de sódio, hidróxido de potássio, hidróxido de sódio, acetato de magnésio, prolina, glicose, glicina, alanina, serina, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, cloridrato de histidina, clorid",
			"cloreto de cálcio diidratado, acetato de sódio, hidróxido de potássio, hidróxido de sódio, prolina, glicose, glicina, alanina, serina, ácido aspártico, ácido glutâmico, leucina, metionina, fenilalanina, cloridrato de lisina, levovalina, treonina, triptofa",
			"cloreto de cálcio diidratado, bicarbonato de sódio, glicose monoidratada, cloreto de potássio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, bicarbonato de sódio, glicose monoidratada, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, cloreto de cálcio, fosfato de cálcio tribásico, sorbitol, cianocobalamina, fluoreto de sódio",
			"cloreto de cálcio diidratado, cloreto de potássio, cloreto de sódio",
			"cloreto de cálcio diidratado, cloreto de potássio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, glicose monoidratada, lactato de sódio, cloreto de sódio",
			"cloreto de cálcio diidratado, glicose monoidratada, lactato de sódio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, glicose, lactato de sódio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio diidratado, glicose, lactato de sódio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, lactato de sódio, cloreto de potássio, cloreto de sódio",
			"cloreto de cálcio diidratado, lactato de sódio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio diidratado, lactato de sódio, cloreto de sódio, cloreto de magnésio hexaidratado, icodextrina",
			"cloreto de cálcio, acetato de potássio, acetato de sódio, acetato de magnésio, prolina, glicose, glicina, alanina, serina, glicerol, ácido aspártico, ácido glutâmico, leucina, metionina, levovalina, treonina, triptofana, isoleucina, arginina, cloreto de s",
			"cloreto de cálcio, acetato de sódio, citrato de sódio, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, acetato de sódio, cloreto de potássio, cloreto de sódio, cloreto de magnésio, hetamido",
			"cloreto de cálcio, ácido acético, cloreto de potássio, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio, ácido acético, cloreto de sódio, cloreto de magnésio hexaidratado",
			"cloreto de cálcio, bicarbonato de sódio, ácido acético, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, bicarbonato de sódio, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, cloreto de potássio, cloreto de sódio",
			"cloreto de cálcio, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, cloreto de potássio, cloreto de sódio, gelatina",
			"cloreto de cálcio, fibrinogênio, trombina",
			"cloreto de cálcio, fibrinogênio, trombina, aprotinina",
			"cloreto de cálcio, fosfato de cálcio tribásico, ergocalciferol, fluoreto de sódio",
			"cloreto de cálcio, glicose, ácido acético, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, glicose, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, glicose, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, glicose, lactato de sódio, cloreto de sódio",
			"cloreto de cálcio, glicose, lactato de sódio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cálcio, hidróxido de sódio, glicerofosfato de sódio, oleato de sódio, glicose, glicerol, ácido acético, cloreto de potássio, ácido clorídrico, cloreto de magnésio, Poliaminoácidos, óleo de soja, água para injeção",
			"cloreto de cálcio, lactato de sódio, cloreto de potássio, cloreto de sódio",
			"cloreto de cálcio, lactato de sódio, cloreto de sódio, cloreto de magnésio",
			"cloreto de cetilpiridínio",
			"cloreto de cetilpiridínio, ácido ascórbico",
			"cloreto de cetilpiridínio, benzocaína",
			"cloreto de cetilpiridínio, borato de sódio, benzocaína",
			"cloreto de cetilpiridínio, bromidrato de dextrometorfano, succinato de doxilamina",
			"cloreto de cetilpiridínio, dextrometorfano, benzocaína",
			"cloreto de cetilpiridínio, tirotricina, mentol, benzocaína",
			"cloreto de metiltionínio",
			"cloreto de potássio",
			"cloreto de sódio",
			"cloreto de sódio, citrato de potássio",
			"cloreto de sódio, cloreto de benzalcônio",
			"cloreto de sódio, hetamido",
			"cloreto de suxametônio",
			"clorexidina",
			"clorfenesina, cloridrato de tetracaína, valerato de betametasona",
			"cloridrato de adifenina, cloridrato de papaverina, dipirona sódica, metilbrometo de homatropina",
			"cloridrato de adifenina, cloridrato de prometazina, dipirona sódica",
			"cloridrato de alfentanila",
			"cloridrato de alfuzosina",
			"cloridrato de alizaprida",
			"cloridrato de amantadina",
			"cloridrato de ambroxol",
			"cloridrato de amilorida, clortalidona",
			"cloridrato de amilorida, furosemida",
			"cloridrato de amilorida, hidroclorotiazida",
			"cloridrato de aminolevulinato de metila",
			"cloridrato de amiodarona",
			"cloridrato de amitriptilina",
			"cloridrato de amitriptilina, clordiazepóxido",
			"cloridrato de amorolfina",
			"cloridrato de anagrelida",
			"cloridrato de anfepramona",
			"cloridrato de arginina, aspartato de ornitina, citrulina",
			"cloridrato de azelastina",
			"cloridrato de bambuterol",
			"cloridrato de bamifilina",
			"cloridrato de benazepril",
			"cloridrato de benserazida, levodopa",
			"cloridrato de benzidamina",
			"Cloridrato de Besifloxacino",
			"cloridrato de betaistina",
			"cloridrato de betaxolol",
			"cloridrato de biperideno",
			"cloridrato de bromexina",
			"cloridrato de buclizina",
			"cloridrato de buclizina, ácido glutâmico, cloridrato de carnitina, cloridrato de piridoxina, tiamina, cianocobalamina, sulfato de magnésio, sulfato ferroso, fosfato de cálcio dibásico, riboflavina, nicotinamida",
			"cloridrato de buclizina, carnitina, lisina, piridoxina, cianocobalamina, riboflavina, nicotinamida, NC/NI",
			"cloridrato de buclizina, cloridrato de cisteína, cloridrato de piridoxina, cloridrato de lisina, triptofana",
			"cloridrato de buclizina, fosfato de riboflavina, lisina, cafeína, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina, nicotinamida",
			"cloridrato de buclizina, fosfato de riboflavina, lisina, cafeína, cloridrato de tiamina, cianocobalamina, nicotinamida, fosfato de piridoxina",
			"cloridrato de buclizina, lisina, piridoxina, cianocobalamina, triptofana",
			"cloridrato de buclizina, piridoxina, cloridrato de lisina, cianocobalamina, triptofana",
			"cloridrato de buflomedil",
			"cloridrato de bupivacaína",
			"cloridrato de bupivacaína, glicose",
			"cloridrato de bupivacaína, hemitartarato de epinefrina",
			"cloridrato de bupropiona",
			"cloridrato de buspirona",
			"cloridrato de butenafina",
			"cloridrato de cefepima",
			"cloridrato de cetamina",
			"cloridrato de ciclobenzaprina",
			"cloridrato de ciclopentolato",
			"cloridrato de cimetidina",
			"cloridrato de cinacalcete",
			"cloridrato de ciprofloxacino",
			"cloridrato de ciprofloxacino monoidratado",
			"cloridrato de clindamicina",
			"cloridrato de clobutinol",
			"cloridrato de clobutinol, succinato de doxilamina",
			"cloridrato de clomipramina",
			"cloridrato de clonidina",
			"cloridrato de clorpromazina",
			"cloridrato de daunorrubicina",
			"cloridrato de delapril",
			"cloridrato de delapril, dicloridrato de manidipino",
			"cloridrato de dexmedetomidina",
			"cloridrato de dexrrazoxano",
			"cloridrato de difenidramina",
			"cloridrato de difenidramina, aminofilina, cloridrato de piridoxina, guaifenesina",
			"cloridrato de difenidramina, aminofilina, guaifenesina",
			"cloridrato de difenidramina, benzoato de sódio",
			"cloridrato de difenidramina, cânfora, calamina",
			"cloridrato de difenidramina, cloridrato de nafazolina",
			"cloridrato de difenoxilato, sulfato de atropina",
			"cloridrato de diltiazem",
			"cloridrato de dobutamina",
			"cloridrato de donepezila",
			"cloridrato de dopamina",
			"cloridrato de dorzolamida",
			"cloridrato de dorzolamida, maleato de timolol",
			"cloridrato de dorzolamida, timolol",
			"cloridrato de doxiciclina",
			"cloridrato de doxorrubicina",
			"Cloridrato de Dronedarona",
			"cloridrato de duloxetina",
			"cloridrato de efedrina, nitrato de nafazolina",
			"cloridrato de epinastina",
			"cloridrato de epirrubicina",
			"cloridrato de esmolol",
			"cloridrato de etafedrina, succinato de doxilamina, ambufilina, guaifenesina",
			"cloridrato de etilefrina",
			"cloridrato de fenazopiridina",
			"cloridrato de fenazopiridina, nitrofurantoína, sulfametoxipiridazina",
			"cloridrato de fenazopiridina, sulfametoxazol, trimetoprima",
			"cloridrato de fenilefrina",
			"cloridrato de fenilefrina, álcool polivinílico",
			"cloridrato de fenilefrina, maleato de bronfeniramina",
			"cloridrato de fenoxazolina",
			"cloridrato de fexofenadina",
			"cloridrato de fexofenadina, cloridrato de pseudoefedrina",
			"cloridrato de fingolimode",
			"cloridrato de fluoxetina",
			"cloridrato de ganissetrona",
			"cloridrato de gencitabina",
			"cloridrato de hidralazina",
			"cloridrato de hidromorfona",
			"cloridrato de idarrubicina",
			"cloridrato de imipramina",
			"cloridrato de irinotecano",
			"cloridrato de irinotecano triidratado",
			"cloridrato de isotipendil",
			"cloridrato de lercanidipino",
			"cloridrato de levamisol",
			"cloridrato de levobunolol",
			"cloridrato de levobupivacaína",
			"cloridrato de levomepromazina",
			"cloridrato de lidocaína",
			"cloridrato de lidocaína, cloreto de benzalcônio",
			"cloridrato de lidocaína, mentol, NC/NI",
			"cloridrato de lincomicina",
			"cloridrato de lisozima",
			"cloridrato de lomefloxacino",
			"cloridrato de loperamida",
			"cloridrato de maprotilina",
			"cloridrato de mebeverina",
			"cloridrato de mefloquina",
			"cloridrato de memantina",
			"cloridrato de memantina, cloridrato de memantina",
			"cloridrato de metadona",
			"cloridrato de metformina",
			"cloridrato de metformina, fosfato de sitagliptina",
			"cloridrato de metformina, glimepirida",
			"cloridrato de metformina, vildagliptina",
			"cloridrato de metilfenidato",
			"cloridrato de metipranolol",
			"cloridrato de metoclopramida",
			"cloridrato de metoclopramida, pancreatina, ácido desidrocólico, pepsina, dimeticona, celulase",
			"cloridrato de metoclopramida, pepsina, dimeticona",
			"cloridrato de mianserina",
			"cloridrato de midazolam",
			"cloridrato de minociclina",
			"cloridrato de mitoxantrona",
			"cloridrato de moxifloxacino",
			"cloridrato de nafazolina",
			"cloridrato de nafazolina, ácido pantotênico",
			"cloridrato de nafazolina, cloreto de benzalcônio",
			"cloridrato de nafazolina, cloreto de sódio",
			"cloridrato de nafazolina, cloreto de sódio, cloreto de benzalcônio",
			"cloridrato de nafazolina, maleato de mepiramina",
			"cloridrato de nafazolina, sulfato de zinco",
			"cloridrato de nafazolina, sulfato de zinco heptaidratado",
			"cloridrato de nalbufina",
			"cloridrato de naloxona",
			"cloridrato de naltrexona",
			"cloridrato de naratriptana",
			"cloridrato de nebivolol",
			"cloridrato de nortriptilina",
			"cloridrato de olopatadina",
			"cloridrato de ondansetrona",
			"cloridrato de ondansetrona diidratado",
			"cloridrato de oxibuprocaína",
			"cloridrato de oxibutinina",
			"cloridrato de oxicodona",
			"cloridrato de oximetazolina",
			"cloridrato de oximetazolina, cloreto de benzalcônio",
			"cloridrato de oxitetraciclina",
			"cloridrato de oxitetraciclina, hidrocortisona",
			"cloridrato de oxomemazina, benzoato de sódio, iodeto de potássio, guaifenesina",
			"cloridrato de palonosetrona",
			"cloridrato de papaverina",
			"cloridrato de papaverina, dipirona sódica",
			"cloridrato de papaverina, dipirona sódica, NC/NI",
			"cloridrato de paroxetina",
			"Cloridrato de Pazopanibe",
			"cloridrato de petidina",
			"cloridrato de pilocarpina",
			"cloridrato de pioglitazona",
			"cloridrato de piperidolato, ácido ascórbico, hesperidina",
			"cloridrato de piridoxina, adenosina, metionina, citrato de colina",
			"cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina",
			"cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina, dipirona sódica, carisoprodol",
			"cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina, nicotinamida",
			"cloridrato de piridoxina, cloridrato de tiamina, riboflavina",
			"cloridrato de piridoxina, metionina, citrato de colina",
			"cloridrato de piridoxina, tiamina, cianocobalamina",
			"Cloridrato de Prasugrel",
			"cloridrato de prazosina",
			"cloridrato de prilocaína",
			"cloridrato de procaína",
			"cloridrato de procaína, teofilina, mentol",
			"cloridrato de prometazina",
			"cloridrato de prometazina, adifenina, dipirona sódica",
			"cloridrato de propafenona",
			"cloridrato de propranolol",
			"cloridrato de propranolol, hidroclorotiazida",
			"cloridrato de protamina",
			"cloridrato de proximetacaína",
			"cloridrato de pseudoefedrina, cloridrato de triprolidina",
			"cloridrato de pseudoefedrina, dicloridrato de cetirizina",
			"cloridrato de pseudoefedrina, loratadina",
			"cloridrato de pseudoefedrina, maleato de bronfeniramina",
			"cloridrato de quinapril",
			"cloridrato de quinina, cloridrato de quinina, cloridrato de piridoxina, papaverina",
			"cloridrato de quinina, papaverina",
			"cloridrato de raloxifeno",
			"cloridrato de ranitidina",
			"cloridrato de remifentanila",
			"cloridrato de ropinirol",
			"cloridrato de ropivacaína",
			"cloridrato de selegilina",
			"cloridrato de sertralina",
			"cloridrato de sevelâmer",
			"cloridrato de sibutramina",
			"cloridrato de sibutramina monoidratado",
			"cloridrato de sotalol",
			"cloridrato de tansulosina",
			"cloridrato de terazosina",
			"cloridrato de terbinafina",
			"cloridrato de tetracaína, cloridrato de fenilefrina",
			"cloridrato de tetracaína, hexamidina",
			"cloridrato de tetraciclina",
			"cloridrato de tetramisol",
			"cloridrato de tetrizolina, cloreto de metiltionínio",
			"cloridrato de tetrizolina, sulfato de zinco",
			"cloridrato de tiamina",
			"cloridrato de tiamina, colecalciferol, palmitato de retinol, citrato de cálcio, nicotinamida",
			"cloridrato de ticlopidina",
			"cloridrato de tioridazina",
			"cloridrato de tizanidina",
			"cloridrato de topotecana",
			"cloridrato de tramadol",
			"cloridrato de trazodona",
			"cloridrato de triexifenidil",
			"cloridrato de triprolidina, pseudoefedrina",
			"cloridrato de tromantadina",
			"cloridrato de valaciclovir",
			"cloridrato de vancomicina",
			"cloridrato de vardenafila",
			"cloridrato de vardenafila triidratado",
			"cloridrato de venlafaxina",
			"cloridrato de verapamil",
			"cloridrato de xilometazolina",
			"cloridrato de ziprasidona monoidratado",
			"cloridrato do ácido aminolevulínico",
			"clorofila, eucaliptol, dipirona sódica, terpineol, guaifenesina",
			"clorpropamida",
			"clortalidona",
			"clotrimazol",
			"cloxazolam",
			"clozapina",
			"cobamamida",
			"cobamamida, cloridrato de ciproeptadina",
			"cocarboxilase, ácido ascórbico, glicina, cloridrato de piridoxina, ácido fólico, colecalciferol, cianocobalamina, palmitato de retinol, dexpantenol, riboflavina, nicotinamida",
			"codeína, feniltoloxamina",
			"colagenase",
			"colchicina",
			"colecalciferol",
			"colecalciferol, cianocobalamina, fluoreto de sódio, fosfato de cálcio dibásico diidratado, lactato de cálcio",
			"colecalciferol, citrato de cálcio",
			"colecalciferol, retinol, fosfato de zinco",
			"colesevelam",
			"colestiramina",
			"colina, cianocobalamina (57Co), pantotenato de cálcio, ácido ascórbico, citrato de zinco, acetato de dextroalfatocoferol, ácido fólico, tiamina, metionina, riboflavina, nicotinamida",
			"colistimetato de sódio",
			"complexo osseína-hidroxiapatita",
			"Creatina",
			"cromoglicato dissódico",
			"dabigatrana",
			"dacarbazina",
			"daclizumabe",
			"dactinomicina",
			"dalfopristina, quinupristina",
			"dalteparina sódica",
			"danazol",
			"dantroleno sódico",
			"dapoxetina",
			"dapsona",
			"daptomicina",
			"darifenacina",
			"darunavir",
			"dasatinibe",
			"decanoato de haloperidol",
			"decanoato de nandrolona",
			"decitabina",
			"deferasirox",
			"deferiprona",
			"deflazacorte",
			"deltametrina",
			"desflurano",
			"deslanosídeo",
			"desloratadina",
			"desloratadina, pseudoefedrina",
			"desogestrel",
			"desogestrel, etinilestradiol",
			"desonida",
			"desoximetasona",
			"dexametasona",
			"dexametasona, cloranfenicol",
			"dexametasona, cloridrato de ciprofloxacino",
			"dexametasona, cloridrato de ciprofloxacino monoidratado",
			"dexametasona, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina",
			"dexametasona, cloridrato de piridoxina, tiamina, cianocobalamina",
			"dexametasona, cloridrato de tetrizolina, cloranfenicol",
			"dexametasona, nitrato de tiamina, cloridrato de piridoxina, cianocobalamina",
			"dexametasona, tiamina, piridoxina, cianocobalamina",
			"dexclorfeniramina",
			"dexclorfeniramina, pseudoefedrina, guaifenesina",
			"dexpantenol",
			"dextrana, hipromelose",
			"dextroalfatocoferol",
			"dextroalfatocoferol, ácido fólico",
			"dextroalfatocoferol, piridoxina, retinol",
			"dextrometorfano",
			"diacereína",
			"diatrizoato de meglumina",
			"diatrizoato de meglumina, diatrizoato de sódio",
			"diazepam",
			"diazepam, fenitoína",
			"diazóxido",
			"dicicloverina",
			"diclofenaco",
			"diclofenaco colestiramina",
			"diclofenaco dietilamônio",
			"diclofenaco potássico",
			"diclofenaco sódico",
			"diclofenaco sódico, fosfato de codeína",
			"diclofenaco, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina",
			"diclofenaco, cloridrato de piridoxina, tiamina, cianocobalamina",
			"dicloridrato de cetirizina",
			"dicloridrato de flufenazina",
			"dicloridrato de flunarizina",
			"dicloridrato de hidroxizina",
			"dicloridrato de manidipino",
			"dicloridrato de pramipexol",
			"dicloridrato de trifluoperazina",
			"dicloridrato de trimetazidina",
			"didanosina",
			"didrogesterona",
			"dienogeste, valerato de estradiol",
			"dietilestilbestrol",
			"difenidramina, cânfora, calamina",
			"difosfato de cloroquina",
			"difumarato de emedastina",
			"digoxina",
			"diltiazem",
			"dimenidrinato",
			"dimenidrinato, cloridrato de piridoxina",
			"dimenidrinato, piridoxina",
			"dimercaprol",
			"dimesilato de almitrina",
			"Dimesilato de Lisdexanfetamina",
			"dimeticona",
			"dinitrato de isossorbida",
			"dinoprostona",
			"dipiridamol",
			"dipirona sódica",
			"dipirona sódica monoidratada",
			"dipirona sódica monoidratada, adifenina",
			"dipirona sódica, codeína",
			"dipirona sódica, homatropina",
			"dipropionato de beclometasona",
			"dipropionato de betametasona",
			"dipropionato de betametasona, ácido salicílico",
			"dipropionato de betametasona, cetoconazol",
			"dissulfiram",
			"ditosilato de lapatinibe",
			"divalproato de sódio",
			"dobesilato de cálcio",
			"docetaxel",
			"docetaxel triidratado",
			"docusato de sódio, bisacodil",
			"dolasetrona",
			"domperidona",
			"doripenem",
			"doxazosina",
			"doxiciclina",
			"doxiciclina monoidratada",
			"doxorrubicina",
			"droperidol",
			"dropropizina",
			"drospirenona",
			"drospirenona, estradiol hemiidratado",
			"dutasterida",
			"ebastina",
			"efavirenz",
			"efedrina, eucaliptol, mentol",
			"ELTROMBOPAG OLAMINA",
			"embonato de imipramina",
			"embonato de pirantel",
			"embonato de pirvínio",
			"enantato de estradiol, algestona",
			"enantato de estradiol, algestona acetonida",
			"enantato de flufenazina",
			"enantato de noretisterona, valerato de estradiol",
			"enflurano",
			"enoxaparina sódica",
			"entacapona",
			"entacapona, carbidopa, levodopa",
			"entecavir",
			"enxofre",
			"enxofre, peróxido de benzoíla",
			"epinefrina",
			"ergocalciferol, palmitato de retinol",
			"ergocalciferol, retinol",
			"ergotamina, cafeína, dipirona sódica",
			"eritromicina",
			"eritromicina, isotretinoína",
			"eritropoietina",
			"erlotinibe",
			"ertapeném sódico",
			"escina sódica, salicilato de dietilamônio, escina",
			"escopolamina",
			"escopolamina, dipirona sódica",
			"esomeprazol magnésio",
			"esomeprazol magnésio, naproxeno",
			"esomeprazol sódico",
			"espiramicina",
			"espironolactona",
			"espironolactona, furosemida",
			"espironolactona, hidroclorotiazida",
			"estavudina",
			"estazolam",
			"estearato de eritromicina",
			"ÉSTERES ETÍLICOS DOS ÁCIDOS GRAXOS DO ÓLEO DE PAPOULA IODADOS",
			"estolato de eritromicina",
			"estradiol",
			"estradiol hemiidratado",
			"estradiol, acetato de noretisterona",
			"estradiol, algestona",
			"estradiol, estradiol",
			"estradiol, gestodeno",
			"estradiol, noretisterona",
			"estradiol, trimegestona",
			"estreptoquinase",
			"estriol",
			"estrogênios conjugados",
			"etabonato de loteprednol",
			"etambutol",
			"etanercepte",
			"etinilestradiol, cloridrato de piridoxina, levonorgestrel",
			"etinilestradiol, drospirenona",
			"etinilestradiol, gestodeno",
			"etinilestradiol, levonorgestrel",
			"etinilestradiol, noretisterona",
			"etinilestradiol, norgestrel",
			"etinilestradiol, piridoxina, levonorgestrel",
			"etionamida",
			"etodolaco",
			"etofamida",
			"etofenamato",
			"etomidato",
			"etonogestrel",
			"etonogestrel, etinilestradiol",
			"etoposídeo",
			"etoricoxibe",
			"etossuximida",
			"Etravirina",
			"eucaliptol, ácido ascórbico, dipirona sódica monoidratada, guaiacol",
			"eucaliptol, ácido benzóico, mentol",
			"eucaliptol, benzoato de sódio, terpina, mentol",
			"eucaliptol, cânfora, mentol",
			"eucaliptol, cânfora, terpineol, gomenol, mentol, guaiacol",
			"everolimo",
			"exametazima",
			"exemestano",
			"exenatida",
			"ezetimiba",
			"ezetimiba, sinvastatina",
			"famotidina",
			"fanciclovir",
			"fator IX de coagulação",
			"fator VII de coagulação , fator IX de coagulação, fator X de coagulação , fator II de coagulação",
			"fator VIII de coagulação",
			"fator VIII de coagulação , fator de von Willebrand",
			"fator XIII de coagulação",
			"felodipino",
			"femprocumona",
			"fempropionato de testosterona, isocaproato de testosterona, benzoato de estradiol",
			"femproporex",
			"fencanfamina, fator VIII de coagulação",
			"fendizoato de cloperastina",
			"Fendizoato de Levocloperastina",
			"fenilalanina, bronfeniramina",
			"fenilbutazona cálcica",
			"fenilefrina, bronfeniramina",
			"fenitoína",
			"fenitoína sódica",
			"fenobarbital",
			"fenofibrato",
			"fenol, cloridrato de procaína",
			"fenol, epinefrina, mentol, benzocaína",
			"fenol, mentol",
			"fenolsulfonato de zinco, cloridrato de nafazolina",
			"fenolsulfonato de zinco, cloridrato de nafazolina, sulfato de berberina",
			"fenolsulfonato de zinco, cloridrato de nafazolina, sulfato de berberina, cloreto de benzalcônio",
			"fenoprofeno cálcico",
			"fenoxazolina",
			"fenoximetilpenicilina",
			"fenoximetilpenicilina potássica",
			"fentanila",
			"ferripolimaltose",
			"ferrocarbonila",
			"ferrocarbonila, pantotenato de cálcio, nitrato de tiamina, cloridrato de piridoxina, ácido fólico, cianocobalamina, riboflavina, nicotinamida",
			"ferrro aminoacido quelato",
			"fibrinogênio",
			"fibrinogênio, trombina",
			"fibrinogênio, trombina, aprotinina",
			"fibrinogênio, trombina, fator XIII de coagulação , aprotinina",
			"fibrinolisina",
			"filgrastim",
			"finasterida",
			"fitomenadiona",
			"fluconazol",
			"fludroxicortida",
			"flufenazina, bendroflumetiazida",
			"flumazenil",
			"flunarizina",
			"flunitrazepam",
			"fluoreto de sódio",
			"fluormetolona",
			"fluoruracila",
			"fluoxetina",
			"flurazepam",
			"flurbiprofeno",
			"flurbiprofeno sódico",
			"flutamida",
			"fluticasona",
			"flutrimazol",
			"fluvastatina",
			"fluvastatina sódica",
			"folinato de cálcio",
			"fondaparinux sódico",
			"fosamprenavir",
			"fosfatidilserina",
			"fosfato de cálcio tribásico",
			"fosfato de cálcio tribásico, cianocobalamina, fluoreto de sódio",
			"fosfato de cálcio tribásico, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina, riboflavina, nicotinamida",
			"fosfato de cálcio tribásico, colecalciferol",
			"fosfato de cálcio tribásico, colecalciferol, cianocobalamina",
			"fosfato de cálcio tribásico, colecalciferol, cianocobalamina, fluoreto de sódio, lactato de cálcio",
			"fosfato de cálcio tribásico, ergocalciferol, cianocobalamina",
			"fosfato de cálcio tribásico, ergocalciferol, cianocobalamina, fluoreto de sódio",
			"fosfato de cálcio tribásico, fluoreto de sódio",
			"fosfato de clindamicina",
			"fosfato de clindamicina, tretinoína",
			"fosfato de codeína",
			"fosfato de disopiramida",
			"fosfato de fludarabina",
			"fosfato de magnésio monobásico",
			"fosfato de magnésio monobásico, calcitriol, ácido ascórbico, dextroalfatocoferol, tiamina, cianocobalamina, retinol, iodo, sulfato de manganês, riboflavina, nicotinamida",
			"fosfato de magnésio monobásico, piridoxina, nicotinamida",
			"fosfato de oseltamivir",
			"fosfato de potássio dibásico, fosfato de potássio monobásico",
			"fosfato de sitagliptina",
			"fosfato de sódio dibásico, ácido fosfórico",
			"fosfato de sódio dibásico, fosfato de sódio monobásico",
			"fosfato de sódio monobásico diidratado",
			"fosfato de sódio monobásico monoidratado, fosfato de sódio dibásico heptaidratado",
			"fosfato de tetraciclina",
			"fosfato de tetraciclina, anfotericina B",
			"fosfato dissódico de betametasona",
			"fosfato dissódico de betametasona, acetato de betametasona",
			"fosfato dissódico de betametasona, betametasona",
			"fosfato dissódico de betametasona, dipropionato de betametasona",
			"fosfato dissódico de dexametasona",
			"fosfato dissódico de dexametasona, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina",
			"fosfato sódico de metilprednisolona",
			"fosfato sódico de prednisolona",
			"fosfato sódico de riboflavina, ácido ascórbico, frutose, cloridrato de piridoxina, nicotinamida",
			"fosfato sódico de riboflavina, cloridrato de piridoxina, cloridrato de lisina, cloridrato de tiamina, colecalciferol, acetato de racealfatocoferol, dexpantenol, lactato de cálcio, nicotinamida",
			"fosfato sódico de riboflavina, cloridrato de piridoxina, cloridrato de tiamina, dexpantenol, nicotinamida",
			"fosfato sódico de riboflavina, frutose, cloridrato de piridoxina, nicotinamida",
			"fosfato sódico de riboflavina, pantenol, ácido ascórbico, cloridrato de piridoxina, acetato de dextroalfatocoferol, ácido fólico, cloridrato de tiamina, colecalciferol, cianocobalamina, palmitato de retinol, nicotinamida",
			"fosfato sódico de riboflavina, pantenol, ácido ascórbico, cloridrato de piridoxina, dextroalfatocoferol, ácido fólico, cloridrato de tiamina, colecalciferol, cianocobalamina, palmitato de retinol, nicotinamida",
			"fosfato sódico de riboflavina, pantotenato de cálcio, glutamato de sódio monobásico, ácido ascórbico, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina, nicotinamida",
			"fosfomicina trometamol",
			"fosinopril",
			"fosinopril sódico",
			"fotemustina",
			"frutose",
			"fulvestranto",
			"fumarato de benciclano",
			"fumarato de bisoprolol",
			"fumarato de bisoprolol, hidroclorotiazida",
			"fumarato de cetotifeno",
			"fumarato de clemastina",
			"fumarato de clemastina, dexametasona",
			"fumarato de formoterol",
			"fumarato de formoterol diidratado, budesonida",
			"fumarato de formoterol, budesonida",
			"fumarato de formoterol, dipropionato de beclometasona",
			"fumarato de quetiapina",
			"fumarato de rupatadina",
			"fumarato de tenofovir desoproxila",
			"fumarato ferroso, ácido ascórbico, ácido fólico, cianocobalamina",
			"furazolidona",
			"furoato de mometasona",
			"furosemida",
			"furosemida, cloreto de potássio",
			"fusafungina",
			"gabapentina",
			"gadobutrol",
			"gadodiamida",
			"gadopentetato de dimeglumina",
			"gadoteridol",
			"gadoversetamida",
			"galantamina",
			"ganciclovir",
			"ganciclovir sódico",
			"gangliosídeos",
			"gatifloxacino",
			"gatifloxacino, acetato de prednisolona",
			"gefitinibe",
			"gelatina, trombina",
			"gemifloxacino",
			"genfibrozila",
			"gentamicina",
			"gentamicina, desoxirribonuclease, fibrinolisina",
			"gestrinona",
			"glibenclamida",
			"glibenclamida, cloridrato de metformina",
			"glicametacina",
			"glicerofosfato de sódio",
			"glicerol",
			"glicerol, dextrana, hipromelose",
			"glicerol, óleo de soja, lecitina de ovo",
			"glicina",
			"glicinato de alumínio, ácido acetilsalicílico, carbonato de magnésio",
			"glicinato de cálcio, ácido acetilsalicílico, carbonato de magnésio",
			"glicinato férrico",
			"glicinato férrico, tiamina, cianocobalamina, dexpantenol, riboflavina, nicotinamida",
			"gliclazida",
			"gliconato de cálcio",
			"gliconato de clorexidina",
			"gliconato de magnésio, cloridrato de piridoxina",
			"gliconato de sódio, acetato de sódio triidratado, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"glicosamina",
			"glicosamina, condroitina",
			"glicose",
			"glicose monoidratada",
			"glicose monoidratada, cloreto de sódio",
			"glicose, citrato de potássio monoidratado, citrato de sódio diidratado, cloreto de sódio",
			"glicose, citrato de sódio diidratado, cloreto de potássio, cloreto de sódio",
			"glicose, citrato de sódio, cloreto de potássio, cloreto de sódio",
			"glicose, citrato de sódio, cloreto de sódio, citrato de potássio",
			"glicose, cloreto de sódio",
			"glicose, dimenidrinato, frutose, cloridrato de piridoxina",
			"glimepirida",
			"glipizida",
			"glucagon",
			"glutamato de cálcio, glutamina, cloridrato de piridoxina, fosfato de ditetraetilamônio",
			"glutamato de sódio monobásico, NC/NI",
			"Golimumabe",
			"gonadotropina coriônica",
			"Gonadotropina Menopausal Humana",
			"gonadotropina sérica",
			"gramicidina, sulfato de framicetina, cloridrato de procaína, prednisolona, cloridrato de amilocaína",
			"granisetrona",
			"griseofulvina",
			"guaifenesina",
			"haloperidol",
			"halotano",
			"hemitartarato de epinefrina",
			"hemitartarato de epinefrina, cloridrato de lidocaína",
			"hemitartarato de metaraminol",
			"hemitartarato de norepinefrina",
			"hemitartarato de rivastigmina",
			"hemitartarato de zolpidem",
			"heparina sódica",
			"heparina sódica, alantoína",
			"heparina sódica, cumarina",
			"heparina sódica, nicotinato de benzila",
			"hesperidina, diosmina",
			"hetamido",
			"hexacetonida de triancinolona",
			"hexaidrobenzoato de estradiol",
			"hialuronato de sódio",
			"hialuronidase",
			"hiclato de doxiciclina",
			"hidroclorotiazida",
			"hidroclorotiazida, bisoprolol",
			"hidroclorotiazida, captopril",
			"hidroclorotiazida, cilazapril",
			"hidroclorotiazida, cloridrato de benazepril",
			"hidroclorotiazida, fosinopril",
			"hidroclorotiazida, lisinopril",
			"hidroclorotiazida, maleato de enalapril",
			"hidroclorotiazida, ramipril",
			"hidroclorotiazida, succinato de metoprolol",
			"hidrocortisona",
			"hidrocortisona, ciprofloxacino",
			"hidrocortisona, cloridrato de ciprofloxacino monoidratado",
			"hidroquinidina, tretinoína, fluocinolona acetonida",
			"hidroquinona",
			"hidroquinona, ácido glicólico",
			"hidroquinona, tretinoína, fluclorolona acetonida",
			"hidroquinona, tretinoína, fluocinolona acetonida",
			"hidroxibenzoato de viminol",
			"hidróxido de alumínio",
			"hidróxido de alumínio, ácido acetilsalicílico, cafeína, maleato de mepiramina",
			"hidróxido de alumínio, ácido acetilsalicílico, cafeína, mepiramina",
			"hidróxido de alumínio, carbonato de magnésio",
			"hidróxido de alumínio, dimeticona",
			"hidróxido de alumínio, pectina, NC/NI",
			"hidróxido de magnésio",
			"hidróxido de magnésio, hidróxido de alumínio",
			"hidróxido de magnésio, hidróxido de alumínio, almagato, dimeticona",
			"hidróxido de magnésio, hidróxido de alumínio, carbonato de cálcio",
			"hidróxido de magnésio, hidróxido de alumínio, diastase, dimeticona",
			"hidróxido de magnésio, hidróxido de alumínio, dimeticona",
			"hidróxido de magnésio, hidróxido de alumínio, metilcelulose, dimeticona",
			"hidróxido de magnésio, hidróxido de alumínio, simeticona",
			"hidróxido de magnésio, trissilicato de magnésio, hidróxido de alumínio, metilcelulose",
			"hidróxido de sódio",
			"hidroxiuréia",
			"hidroxizina",
			"hidroxocobalamina",
			"hidroxocobalamina, dexametasona, tiamina, piridoxina",
			"hidroxocobalamina, dipirona sódica",
			"hipromelose",
			"homatropina, dimeticona",
			"ibuprofeno",
			"ibuprofeno, arginina",
			"idoxuridina",
			"Idursulfase",
			"ifosfamida",
			"iloprosta",
			"imiglucerase",
			"imipeném monoidratado",
			"imipeném monoidratado, cilastatina sódica",
			"imipeném, cilastatina sódica",
			"imipramina",
			"imiquimode",
			"imunoglobulina anti-citomegalovírus",
			"imunoglobulina anti-Rho(D)",
			"imunoglobulina antitimócito",
			"imunoglobulina g",
			"imunoglobulina humana",
			"imunoglobulinas",
			"indapamida",
			"indapamida, perindopril",
			"indometacina",
			"infliximabe",
			"insulina asparte",
			"insulina bifásica",
			"insulina detemir",
			"insulina glargina",
			"insulina glulisina",
			"insulina humana",
			"insulina isofana",
			"insulina lispro",
			"insulina neutra",
			"iobitridol",
			"iodeto de potássio",
			"iodeto de potássio, guaifenesina",
			"iodeto de potássio, mentol, guaifenesina",
			"iodixanol",
			"iodopovidona",
			"ioexol",
			"ioimbina",
			"iopamidol",
			"iopromida",
			"iotalamato de meglumina",
			"ioversol",
			"ioxitalamato de meglumina, ioxitalamato de sódio",
			"ioxitalamato de meglumina, povidona",
			"ipriflavona",
			"irbesartana",
			"irbesartana, hidroclorotiazida",
			"isetionato de pentamidina",
			"isocaproato de testosterona, decanoato de testosterona, propionato de testosterona",
			"isoflurano",
			"isometepteno",
			"isometepteno, cafeína, dipirona sódica",
			"isoniazida",
			"isotretinoína",
			"isoxsuprina",
			"isradipino",
			"itraconazol",
			"ivabradina",
			"ivermectina",
			"lacidipino",
			"lactato de amônio",
			"lactato de biperideno",
			"lactato de milrinona",
			"lactato de sódio, cloreto de potássio, cloreto de sódio, cloreto de magnésio",
			"lactitol",
			"lactulose",
			"lamivudina",
			"lamivudina, sulfato de abacavir",
			"lamivudina, zidovudina",
			"lamotrigina",
			"lanolina anidra, dexpantenol",
			"lansoprazol",
			"lansoprazol, amoxicilina triidratada, claritromicina",
			"lansoprazol, amoxicilina, claritromicina",
			"lansoprazol, bromoprida",
			"lansoprazol, claritromicina",
			"lansoprazol, domperidona",
			"laronidase",
			"latanoprosta",
			"latanoprosta, maleato de timolol",
			"laurilsulfato de sódio, sorbitol",
			"lecitina de soja",
			"leflunomida",
			"lenograstim",
			"lercanidipino",
			"letrozol",
			"levocarnitina",
			"levocetirizina",
			"levodopa",
			"levodropropizina",
			"levofloxacino",
			"levofloxacino, lansoprazol, amoxicilina triidratada",
			"levonorgestrel",
			"levonorgestrel, valerato de estradiol",
			"levosimendana",
			"levossulpirida",
			"levotiroxina sódica",
			"lidocaína",
			"lidocaína, cansilato de sódio, eucaliptol, gomenol, guaifenesina",
			"lidocaína, fosfato dissódico de dexametasona, cloridrato de piridoxina, cloridrato de tiamina, cianocobalamina",
			"lidocaína, mentol",
			"lidocaína, neomicina, hialuronidase",
			"lidocaína, neomicina, polimixina B, fluocinolona acetonida",
			"lidocaína, polidocanol",
			"lidocaína, prilocaína",
			"lidocaína, sulfato de neomicina, sulfato de polimixina B, fluocinolona acetonida",
			"lidocaína, sulfato de polimixina B",
			"lidocaína, tirotricina, brometo de cetrimônio",
			"lidocaína, tirotricina, cetrimida, ácido ascórbico",
			"limeciclina",
			"Linagliptina",
			"lincomicina",
			"linestrenol",
			"linestrenol, etinilestradiol",
			"linezolida",
			"liraglutida",
			"lisina, cafeína, tiamina, buclizina, nicotinamida",
			"lisinato de cetoprofeno",
			"lisinopril",
			"lomifilina, mesilato de diidroergocristina",
			"lomustina",
			"loperamida",
			"lopinavir",
			"loratadina",
			"loratadina, pseudoefedrina",
			"lorazepam",
			"lornoxicam",
			"losartana",
			"losartana potássica",
			"losartana potássica, hidroclorotiazida",
			"losartana, hidroclorotiazida",
			"losartana, losartana potássica",
			"loteprednol, tobramicina",
			"lovastatina",
			"loxoprofeno sódico diidratado",
			"macrogol",
			"magaldrato",
			"magaldrato, dimeticona",
			"malato de sunitinibe",
			"maleato de clorfeniramina, ácido acetilsalicílico, cafeína",
			"maleato de clorfeniramina, ácido ascórbico, dipirona sódica, NC/NI",
			"maleato de clorfeniramina, cafeína, dipirona sódica",
			"maleato de dexbronfeniramina, sulfato de pseudoefedrina",
			"maleato de dexclorfeniramina",
			"maleato de dexclorfeniramina, ácido ascórbico, cafeína, salicilamida",
			"maleato de dexclorfeniramina, betametasona",
			"maleato de dexclorfeniramina, dexametasona",
			"maleato de dexclorfeniramina, guaiacol, pseudoefedrina",
			"maleato de dexclorfeniramina, sulfato de pseudoefedrina, guaifenesina",
			"maleato de enalapril",
			"maleato de enalapril, clortalidona",
			"maleato de ergometrina",
			"maleato de feniramina, cloridrato de nafazolina",
			"maleato de flupirtina",
			"maleato de fluvoxamina",
			"maleato de indacaterol",
			"maleato de levomepromazina",
			"maleato de metilergometrina",
			"maleato de midazolam",
			"maleato de pimetixeno",
			"maleato de timolol",
			"maleato de timolol, tartarato de brimonidina",
			"maleato de trimebutina",
			"manitol",
			"maraviroque",
			"mazindol",
			"mebendazol",
			"meclozina",
			"mecobalamina",
			"medroxiprogesterona",
			"melfalana",
			"meloxicam",
			"meloxicam, meloxicam",
			"memantina",
			"mentol",
			"mepartricina, cloridrato de tetraciclina",
			"mercaptopurina",
			"meropeném",
			"meropeném triidratado",
			"mesalazina",
			"mesilato de bromocriptina",
			"mesilato de codergocrina",
			"mesilato de desferroxamina",
			"mesilato de diidroergocristina",
			"mesilato de diidroergocristina, dicloridrato de flunarizina",
			"mesilato de diidroergocristina, piracetam",
			"mesilato de doxazosina",
			"mesilato de fentolamina",
			"mesilato de imatinibe",
			"mesilato de nelfinavir",
			"mesilato de pefloxacino",
			"mesilato de saquinavir",
			"mesna",
			"mesterolona",
			"metenamina, cloreto de metiltionínio",
			"metenamina, cloreto de metiltionínio, cloridrato de acriflavina",
			"metformina",
			"metformina, glimepirida",
			"metilbrometo de homatropina",
			"metilbrometo de homatropina, dimeticona",
			"metildigoxina",
			"metildopa",
			"metilprednisolona",
			"metilsulfato de neostigmina",
			"metilsulfato de pralidoxima",
			"metionina",
			"metionina, citrato de colina, nicotinamida",
			"metionina, cloreto de colina",
			"metionina, silimarina",
			"metisergida",
			"metoclopramida",
			"metotrexato",
			"metoxisaleno",
			"metronidazol",
			"metronidazol, espiramicina",
			"micafungina",
			"micofenolato de mofetila",
			"micofenolato de sódio",
			"miconazol",
			"midazolam",
			"miglustate",
			"minoxidil",
			"mirtazapina",
			"misoprostol",
			"mitomicina",
			"mitotano",
			"mitoxantrona",
			"moclobemida",
			"modafinila",
			"molgramostim",
			"mometasona",
			"mononitrato de isossorbida",
			"mononitrato de isossorbida, ácido acetilsalicílico",
			"montelucaste",
			"montelucaste de sódio",
			"moxifloxacino",
			"moxifloxacino, dexametasona",
			"moxonidina",
			"mucopolissacaridase",
			"mupirocina",
			"muromonabe CD3",
			"nadolol",
			"nadroparina cálcica",
			"naftidrofurila",
			"nandrolona",
			"naproxeno",
			"naproxeno sódico",
			"napsilato de dextropropoxifeno, ácido acetilsalicílico",
			"natalizumabe",
			"nateglinida",
			"nateglinida, cloridrato de metformina",
			"NC/NI",
			"neomicina",
			"neomicina, bacitracina",
			"neomicina, betametasona, cetoconazol",
			"neomicina, dexametasona",
			"neomicina, dexametasona, nafazolina",
			"neomicina, tartarato de bismuto e sódio",
			"neomicina, tartarato de bismuto e sódio, cloridrato de procaína, mentol",
			"neomicina, tiabendazol",
			"neomicina, valerato de betametasona",
			"nepafenaco",
			"nesiritida",
			"nevirapina",
			"nicergolina",
			"niclosamida",
			"nicotina",
			"nicotinamida",
			"nifedipino",
			"nifedipino, ácido acetilsalicílico",
			"nifedipino, atenolol",
			"nifuroxazida",
			"nilutamida",
			"nimesulida",
			"nimesulida betaciclodextrina",
			"nimodipino",
			"nimotuzumabe",
			"nistatina",
			"nistatina, cloranfenicol, nimorazol",
			"nistatina, metronidazol",
			"nistatina, metronidazol, cloreto de benzalcônio, lisozima",
			"nistatina, metronidazol, uréia, cloreto de benzalcônio",
			"nistatina, metronidazol, uréia, cloreto de benzalcônio, cloridrato de lisozima",
			"nistatina, neomicina, gramicidina, triancinolona acetonida",
			"nistatina, neomicina, tirotricina, dexametasona",
			"nistatina, sulfato de neomicina, gramicidina",
			"nistatina, sulfato de neomicina, gramicidina, triancinolona acetonida",
			"nistatina, sulfato de neomicina, sulfato de polimixina B, tinidazol",
			"nistatina, sulfato de neomicina, triancinolona acetonida",
			"nitazoxanida",
			"nitrato ceroso, sulfadiazina de prata",
			"nitrato de butoconazol",
			"nitrato de fenticonazol",
			"nitrato de isoconazol",
			"nitrato de isoconazol, valerato de diflucortolona",
			"nitrato de miconazol",
			"nitrato de miconazol, tioconazol",
			"nitrato de nafazolina",
			"nitrato de nafazolina, sulfato de zinco",
			"nitrato de oxiconazol",
			"nitrato de prata",
			"nitrato de tiamina, cloridrato de piridoxina, cianocobalamina",
			"nitrazepam",
			"nitrendipino",
			"nitrofural",
			"nitrofurantoína",
			"nitroglicerina",
			"nitroprusseto de sódio",
			"nizatidina",
			"nonoxinol",
			"norelgestromina, etinilestradiol",
			"noretisterona",
			"noretisterona, valerato de estradiol",
			"norfloxacino",
			"norgestimato, estradiol",
			"nortriptilina",
			"ocitocina",
			"octreotida",
			"ofloxacino",
			"olanzapina",
			"oleato de monoetanolamina",
			"óleo de soja",
			"óleo de soja, NC/NI",
			"óleo de soja, óleo de oliva",
			"óleo de soja, óleo de oliva, NC/NI",
			"olivomicina, óleo de soja",
			"olmesartana",
			"olmesartana medoxomila",
			"olmesartana medoxomila, anlodipino",
			"olmesartana medoxomila, hidroclorotiazida",
			"omalizumabe",
			"omeprazol",
			"omeprazol magnésico",
			"omeprazol sódico",
			"ondansetrona",
			"oprelvecina",
			"orlistate",
			"oseltamivir",
			"oxacilina",
			"oxacilina sódica",
			"oxalato de escitalopram",
			"oxaliplatina",
			"oxamniquina",
			"oxcarbazepina",
			"oxetacaína, hidróxido de magnésio, hidróxido de alumínio",
			"óxido cúprico, fumarato ferroso, ácido ascórbico, acetato de dextroalfatocoferol, ácido fólico, tiamina, piridoxina, cianocobalamina, sulfato de zinco, riboflavina, nicotinamida",
			"óxido de magnésio, hidróxido de alumínio, dimeticona",
			"óxido de magnésio, óxido de zinco, ácido ascórbico, betacaroteno, acetato de racealfatocoferol, NC/NI",
			"óxido de magnésio, óxido de zinco, carbonato de cálcio, colecalciferol, sulfato cúprico, NC/NI, sulfato de manganês monoidratado",
			"óxido de magnésio, óxido de zinco, carbonato de cálcio, colecalciferol, sulfato cúprico, sulfato de manganês monoidratado",
			"óxido de zinco",
			"óxido de zinco, cânfora, cloreto de benzalcônio",
			"óxido de zinco, cloridrato de difenidramina, cânfora, calamina",
			"óxido de zinco, colecalciferol, palmitato de retinol",
			"óxido de zinco, colecalciferol, retinol",
			"óxido de zinco, ergocalciferol, retinol",
			"óxido de zinco, lidocaína, acetato de hidrocortisona, subacetato de alumínio",
			"óxido de zinco, nistatina",
			"óxido de zinco, óxido cúprico, ácido ascórbico, betacaroteno, acetato de racealfatocoferol",
			"óxido de zinco, peróxido de zinco, sulfato de neomicina, sulfato de polimixina B, bacitracina",
			"óxido férrico",
			"oximetolona",
			"oxomemazina, benzoato de sódio, iodeto de potássio, guaifenesina",
			"paclitaxel",
			"paclitaxel, paclitaxel",
			"paliperidona",
			"palivizumabe",
			"palmitato de neomicina",
			"palmitato de pipotiazina",
			"palmitato de retinol",
			"pamidronato dissódico",
			"pancreatina",
			"pancreatina, diastase, pepsina, nicotinamida",
			"pancreatina, dimeticona",
			"panitumumabe",
			"pantenol, ácido ascórbico, riboflavina",
			"pantenol, carbonato de cálcio, ácido ascórbico, nicotinamida",
			"pantenol, cloridrato de nafazolina, maleato de mepiramina",
			"pantoprazol",
			"pantoprazol sódico",
			"pantoprazol sódico sesquiidratado",
			"pantotenato de cálcio, ácido ascórbico, cloridrato de piridoxina, acetato de dextroalfatocoferol, ácido fólico, tiamina, cianocobalamina, riboflavina, nicotinamida",
			"pantotenato de cálcio, ácido ascórbico, cloridrato de piridoxina, tiamina, riboflavina, nicotinamida",
			"pantotenato de cálcio, ácido ascórbico, frutose, cloridrato de piridoxina, dextroalfatocoferol, tiamina, cianocobalamina, piracetam, riboflavina, nicotinamida",
			"pantotenato de cálcio, ácido fólico, sulfato ferroso, nicotinamida",
			"pantotenato de cálcio, ácido paraminobenzóico, cistina, tiamina, queratina, levedura",
			"pantotenato de cálcio, cloridrato de piridoxina, cloridrato de lisina, cloridrato de tiamina",
			"pantotenato de cálcio, mononitrato de isossorbida, acetato de dextroalfatocoferol, ácido fólico, colecalciferol, cianocobalamina, palmitato de retinol, dexpantenol",
			"pantotenato de cálcio, piridoxina, cloridrato de tiamina, riboflavina, nicotinamida",
			"paracetamol",
			"paracetamol, ácido acetilsalicílico, cafeína",
			"paracetamol, butilbrometo de escopolamina",
			"paracetamol, cafeína",
			"paracetamol, cafeína, carisoprodol",
			"paracetamol, cafeína, cloridrato de fenilefrina",
			"paracetamol, cafeína, cloridrato de piridoxina, tiamina, cianocobalamina, carisoprodol",
			"paracetamol, cafeína, mesilato de diidroergotamina",
			"paracetamol, cafeína, orfenadrina",
			"paracetamol, citrato de orfenadrina, cafeína",
			"paracetamol, citrato de pentoxiverina, maleato de carbinoxamina, cloridrato de fenilefrina",
			"paracetamol, cloridrato de clorfeniramina, cloridrato de fenilefrina",
			"paracetamol, cloridrato de fenilefrina",
			"paracetamol, cloridrato de pseudoefedrina",
			"paracetamol, cloridrato de tramadol",
			"paracetamol, clorzoxazona",
			"paracetamol, codeína",
			"paracetamol, diclofenaco sódico, cafeína, carisoprodol",
			"paracetamol, diclofenaco, cafeína, carisoprodol",
			"paracetamol, diclofenaco, carisoprodol",
			"paracetamol, dropropizina, difenidramina, pseudoefedrina",
			"paracetamol, ergotamina, cafeína, cloridrato de metoclopramida",
			"paracetamol, fosfato de codeína",
			"paracetamol, maleato de carbinoxamina, cloridrato de fenilefrina",
			"paracetamol, maleato de clorfeniramina, cloridrato de fenilefrina",
			"paracetamol, oxomemazina, benzoato de sódio, guaifenesina",
			"paracetamol, rutosídeo, maleato de dimetindeno, ácido ascórbico, cloridrato de fenilefrina",
			"paracetamol, sulfato de atropina, cafeína, sulfato de hiosciamina, tartarato de ergometrina",
			"paracetamol, tartarato de ergotamina, sulfato de atropina, cafeína, sulfato de hiosciamina diidratada",
			"parecoxibe",
			"paricalcitol",
			"paroxetina",
			"paroxetina, cloridrato de paroxetina",
			"pegaptanibe sódico",
			"pegfilgrastim",
			"pegvisomanto",
			"pemetrexede dissódico",
			"penciclovir",
			"penfluridol",
			"penicilamina",
			"pentetrazol, codeína",
			"pentoxifilina",
			"perflutreno",
			"periciazina",
			"perindopril",
			"perindopril erbumina",
			"permetrina",
			"peróxido de benzoíla",
			"peróxido de uréia, peróxido de hidrogênio",
			"picossulfato de sódio",
			"picossulfato de sódio, NC/NI",
			"pidolato de piridoxina",
			"pimecrolimo",
			"pimetixeno",
			"pimozida",
			"pindolol",
			"pindolol, clopamida",
			"pioglitazona, metformina",
			"piperacilina sódica, tazobactam",
			"piperacilina sódica, tazobactam sódico",
			"piperacilina, tazobactam",
			"piracetam",
			"pirazinamida",
			"pirenoxina sódica",
			"piretanida",
			"piribedil",
			"pirimetamina",
			"piroxicam",
			"piroxicam betaciclodextrina",
			"piroxicam, citrato de orfenadrina, dexametasona, cianocobalamina",
			"pivalato de flumetasona, ácido salicílico",
			"pivalato de fluocortolona, caproato de fluocortolona, cloridrato de cinchocaína, undecilato de clemizol",
			"pivalato de fluocortolona, cloridrato de lidocaína",
			"pizotifeno",
			"podofilotoxina",
			"Poliaminoácidos",
			"policarbofila",
			"policresuleno",
			"policresuleno, cloridrato de cinchocaína",
			"poliestirenossulfonato de cálcio",
			"poligelina",
			"polissulfato de mucopolissacarídeo",
			"Polivitamínicos com minerais",
			"Polivitamínicos sem minerais",
			"posaconazol",
			"povidona",
			"pravastatina sódica",
			"praziquantel",
			"prednicarbato",
			"prednisolona",
			"prednisolona, carbonato básico de bismuto",
			"prednisona",
			"pregabalina",
			"primidona",
			"probenecida, ampicilina",
			"progesterona",
			"prolina, cloridrato de ornitina, glicina, alanina, serina, ácido aspártico, ácido glutâmico, tirosina, leucina, metionina, fenilalanina, asparagina, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"prolina, cloridrato de ornitina, glicina, alanina, serina, ácido aspártico, ácido glutâmico, tirosina, leucina, metionina, fenilalanina, cloridrato de lisina, asparagina, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"prolina, cloridrato de ornitina, glicose, cloridrato de cisteína, acetiltirosina, glicina, alanina, serina, ácido aspártico, ácido glutâmico, lisina, tirosina, leucina, metionina, fenilalanina, ácido málico, asparagina, histidina, levovalina, treonina, tr",
			"prolina, glicina, alanina, lisina, leucina, metionina, fenilalanina, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"prolina, glicina, alanina, serina, acetato de lisina, tirosina, acetilcisteína, leucina, metionina, fenilalanina, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"prolina, glicina, alanina, serina, lisina, acetilcisteína, leucina, metionina, fenilalanina, ácido málico, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"prolina, glicina, alanina, serina, lisina, acetilcisteína, leucina, metionina, fenilalanina, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"prolina, glicose, glicina, alanina, serina, lisina, tirosina, leucina, metionina, fenilalanina, histidina, levovalina, treonina, triptofana, isoleucina, arginina, óleo de soja, óleo de oliva",
			"promestrieno",
			"prometazina",
			"propatilnitrato",
			"propifenazona, cafeína, mesilato de diidroergotamina",
			"propilparabeno",
			"propiltiouracila",
			"propionato de clobetasol",
			"propionato de fluticasona",
			"propionato de fluticasona, xinafoato de salmeterol",
			"propofol",
			"propranolol",
			"protease pancreática",
			"rabeprazol sódico",
			"racecadotrila",
			"raltegravir",
			"raltitrexede",
			"ramipril",
			"ramipril, anlodipino",
			"ranelato de estrôncio",
			"ranibizumabe",
			"ranitidina",
			"ranitidina, citrato de bismuto",
			"rasagilina",
			"rasburicase",
			"reboxetina",
			"repaglinida",
			"reserpina, clortalidona",
			"Retapamulina",
			"retinol",
			"ribavirina",
			"rifamicina",
			"rifamicina SV sódica",
			"rifampicina",
			"rifampicina, isoniazida",
			"rilmenidina",
			"riluzol",
			"risedronato sódico",
			"risperidona",
			"ritodrina",
			"ritonavir",
			"ritonavir, lopinavir",
			"rituximabe",
			"Rivaroxabana",
			"rivastigmina",
			"roflumilaste",
			"rosuvastatina",
			"rosuvastatina cálcica",
			"roxitromicina",
			"rutosídeo",
			"sacarato de hidróxido férrico",
			"sacarato de óxido férrico",
			"salbutamol",
			"salbutamol, dipropionato de beclometasona",
			"salicilato de bismuto monobásico",
			"salicilato de dietilamônio, escina",
			"salicilato de fenila, óxido de zinco, ácido salicílico, enxofre, mentol",
			"salicilato de metila",
			"salicilato de metila, cânfora",
			"salicilato de metila, cânfora, mentol",
			"salicilato de metila, cânfora, mentol, terebintina",
			"salicilato de metila, cânfora, mentol, timol",
			"salicilato de metila, cânfora, terebintina",
			"salicilato de metila, levomentol",
			"salicilato de metila, mentol",
			"salicilato de metila, NC/NI, terebintina",
			"salicilato de metila, óxido de zinco, cânfora",
			"salicilato de sódio",
			"sapropterina",
			"saquinavir",
			"saxa gliptina",
			"secnidazol",
			"selegilina",
			"sevoflurano",
			"simeticona",
			"sinvastatina",
			"sirolimo",
			"somatostatina",
			"somatropina",
			"sorbitol",
			"sorbitol, cloridrato de betaína",
			"sorbitol, lactato de cálcio",
			"sorbitol, manitol",
			"sorbitol, metionina, citrato de colina",
			"sorbitol, piridoxina, acetilmetionina, cianocobalamina, citrato de colina",
			"subcitrato de bismuto coloidal",
			"Succinato de desvenlafaxina monoidratado",
			"succinato de estriol",
			"succinato de metoprolol",
			"succinato de sumatriptana",
			"succinato sódico de cloranfenicol",
			"succinato sódico de hidrocortisona",
			"succinato sódico de metilprednisolona",
			"succinilgelatina",
			"sucralfato",
			"Sugamadex",
			"sulbactam sódica, ampicilina",
			"sulbactam sódica, ampicilina sódica",
			"sulbutiamina",
			"sulfabenzamida, sulfacetamida, sulfatiazol",
			"sulfacetamida",
			"sulfacetamida sódica",
			"sulfacrisoidina, cloreto de benzalcônio, benzocaína",
			"sulfadiazina",
			"sulfadiazina de prata",
			"sulfadiazina, trimetoprima",
			"sulfadoxina, pirimetamina",
			"sulfametoxazol",
			"sulfametoxazol, trimetoprima",
			"sulfametoxazol, trimetoprima, fenazopiridina",
			"sulfassalazina",
			"sulfato de abacavir",
			"sulfato de amicacina",
			"sulfato de atazanavir",
			"sulfato de atropina",
			"sulfato de atropina, piperacilina sódica, tazobactam sódico",
			"sulfato de bário",
			"sulfato de bleomicina",
			"sulfato de cefpiroma",
			"sulfato de efedrina",
			"sulfato de efedrina, dicloridrato de hidroxizina, teofilina",
			"sulfato de efedrina, maleato de dexclorfeniramina, guaifenesina",
			"sulfato de efedrina, teofilina",
			"sulfato de estreptomicina",
			"sulfato de estrona",
			"sulfato de gentamicina",
			"sulfato de gentamicina, desonida",
			"sulfato de gentamicina, desoxirribonuclease, fibrinolisina",
			"sulfato de gentamicina, dipropionato de betametasona",
			"sulfato de gentamicina, fosfato dissódico de betametasona",
			"sulfato de gentamicina, valerato de betametasona",
			"sulfato de gentamicina, valerato de betametasona, tolnaftato",
			"sulfato de glicosamina",
			"sulfato de glicosamina, glicosamina, sulfato de condroitina, sulfato de condroitina",
			"sulfato de glicosamina, sulfato de condroitina",
			"sulfato de hidroxicloroquina",
			"sulfato de indinavir",
			"sulfato de magnésio",
			"sulfato de magnésio heptaidratado",
			"sulfato de morfina",
			"sulfato de neomicina",
			"sulfato de neomicina, acetato de clostebol",
			"sulfato de neomicina, acetato de hidrocortisona, ácido ascórbico, troxerrutina",
			"sulfato de neomicina, bacitracina",
			"sulfato de neomicina, bacitracina zíncica",
			"sulfato de neomicina, betametasona, cetoconazol",
			"sulfato de neomicina, desoximetasona",
			"sulfato de neomicina, dexametasona",
			"sulfato de neomicina, dipropionato de betametasona, cetoconazol",
			"sulfato de neomicina, fludroxicortida",
			"sulfato de neomicina, fluocinolona acetonida",
			"sulfato de neomicina, fosfato dissódico de dexametasona",
			"sulfato de neomicina, fosfato dissódico de dexametasona, cloridrato de fenilefrina",
			"sulfato de neomicina, sulfato de polimixina B, acetato de fludrocortisona, cloridrato de lidocaína",
			"sulfato de neomicina, sulfato de polimixina B, acetato de prednisolona",
			"sulfato de neomicina, sulfato de polimixina B, dexametasona",
			"sulfato de neomicina, sulfato de polimixina B, fluocinolona acetonida",
			"sulfato de neomicina, sulfato de polimixina B, fluocinolona acetonida, cloridrato de lidocaína",
			"sulfato de neomicina, sulfato de polimixina B, hidrocortisona",
			"sulfato de neomicina, tiabendazol",
			"sulfato de neomicina, valerato de betametasona",
			"sulfato de polimixina B",
			"sulfato de polimixina B, cloridrato de oxitetraciclina",
			"sulfato de polimixina B, prednisolona",
			"sulfato de pseudoefedrina, loratadina",
			"sulfato de quinina",
			"sulfato de salbutamol",
			"sulfato de salbutamol, dipropionato de beclometasona",
			"sulfato de salbutamol, guaifenesina",
			"sulfato de terbutalina",
			"sulfato de terbutalina, guaifenesina",
			"sulfato de tobramicina",
			"sulfato de trimetoprima, sulfametoxazol",
			"sulfato de vimblastina",
			"sulfato de vincristina",
			"sulfato de vincristina, manitol",
			"sulfato de zinco",
			"sulfato de zinco heptaidratado",
			"sulfato ferroso",
			"sulfato ferroso heptaidratado",
			"sulfeto de selênio",
			"sulfiram",
			"sulfoguaiacol, cloridrato de bromexina",
			"sulpirida",
			"sulpirida, bromazepam",
			"sultamicilina",
			"sumatriptana",
			"tacrolimo",
			"tadalafila",
			"talidomida",
			"tartarato de brimonidina",
			"tartarato de metoprolol",
			"tartarato de metoprolol, hidroclorotiazida",
			"tartarato de tolterodina",
			"tartarato de vareniclina",
			"tartarato de vinorelbina",
			"taurina, aspartato de arginina, fosfato de ditetraetilamônio",
			"taurina, prolina, cisteína, glicina, alanina, serina, acetato de lisina, tirosina, leucina, metionina, fenilalanina, ácido málico, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"taurina, prolina, glicina, alanina, serina, acetato de lisina, tirosina, leucina, metionina, fenilalanina, histidina, levovalina, treonina, triptofana, isoleucina, arginina",
			"teclozana",
			"tecnécio sestamibi 99mTc",
			"tegafur, uracila",
			"tegaserode",
			"teicoplanina",
			"teicoplanina, teicoplanina",
			"telbivudina",
			"telitromicina",
			"telmisartana",
			"telmisartana, hidroclorotiazida",
			"temozolomida",
			"tenecteplase",
			"teniposídeo",
			"tenoxicam",
			"tensirolimo",
			"teofilina",
			"terbinafina",
			"terconazol",
			"teriparatida",
			"terlipressina",
			"terpina monoidratada, eucaliptol, benzoato de sódio, mentol",
			"testosterona",
			"tetraciclina",
			"tetrafluoroborato de cobre (I) tetracis (2-metoxi-isobutil-isonitrila)",
			"tetrofosmina",
			"tiabendazol",
			"tiabendazol, mebendazol",
			"tiamazol",
			"tiamina, cianocobalamina, dipirona sódica",
			"tianeptina",
			"tianfenicol",
			"tibolona",
			"ticagrelor",
			"ticarcilina dissódica, clavulanato de potássio",
			"tigeciclina",
			"timomodulina",
			"timostimulina",
			"tinidazol",
			"tinidazol, miconazol",
			"tinidazol, nitrato de miconazol",
			"tinidazol, secnidazol, tioconazol",
			"tinidazol, tioconazol",
			"tiocolchicosídeo",
			"tioconazol",
			"tioguanina",
			"tiopental sódico",
			"tipranavir",
			"tirofibana",
			"tirotricina",
			"tirotricina, ácido láctico",
			"tirotricina, benzocaína",
			"tirotricina, clorofila",
			"tirotricina, mentol, benzocaína",
			"tirotricina, sulfato de neomicina, dexametasona",
			"tobramicina",
			"tobramicina, dexametasona",
			"tocilizumabe",
			"tolcapona",
			"tolterodina",
			"topiramato",
			"topotecana",
			"tosilato de sorafenibe",
			"tosilato de sultamicilina",
			"toxina botulínica tipo A",
			"trabectedina",
			"trandolapril",
			"tranilcipromina",
			"trapidil",
			"trastuzumabe",
			"travoprosta",
			"travoprosta, maleato de timolol",
			"trazodona",
			"treprostinila sódica",
			"tretinoína",
			"triancinolona acetonida",
			"triancinolona, nistatina, neomicina, gramicidina",
			"triancinolona, nistatina, nistatina, neomicina, sulfato de neomicina, gramicidina, gramicidina, triancinolona acetonida",
			"triantereno, hidroclorotiazida",
			"tribenosídeo",
			"tribenosídeo, lidocaína",
			"triclosana",
			"triflusal",
			"Trióxido de Arsênio",
			"tripsina, quimotripsina",
			"triptorrelina",
			"trolamina, hidroxiquinolina",
			"trometamol cetorolaco",
			"tropicamida",
			"troxerrutina, cumarina",
			"ubidecarenona",
			"undecilato de testosterona",
			"uréia",
			"urofolitropina",
			"ustequinumabe",
			"vacina adsorvida contra difteria, tétano, coqueluche acelular, poliomielite inativada, hepatite B (recombinante) e Haemophilus influenzae tipo b conjugado",
			"vacina adsorvida contra difteria, tétano, coqueluche e poliomelite inativada",
			"vacina BCG",
			"vacina combinada contra difteria, tétano, coqueluche, polioinativado e Haemophilus influenzae tipo b",
			"vacina conjugada contra Haemophilus influenza tipo b (proteína diftérica CRM 197)",
			"vacina contra difteria, tétano e coqueluche",
			"vacina contra febre amarela",
			"Vacina contra Febre Tifóide",
			"vacina contra hepatite A",
			"vacina contra hepatite A, vacina contra hepatite B",
			"vacina contra hepatite B",
			"Vacina contra HPV Oncogênico (16 e 18 recombinante)",
			"vacina contra meningite A e C",
			"vacina contra meningite B e C",
			"vacina contra meningite C",
			"vacina contra pneumococos",
			"vacina contra poliomelite atenuada",
			"vacina contra poliomelite inativada",
			"vacina contra sarampo",
			"vacina contra sarampo e rubéola",
			"vacina contra sarampo, vacina contra rubéola, vacina contra caxumba",
			"vacina contra tétano",
			"vacina contra varicela",
			"valaciclovir",
			"valerato de betametasona",
			"valerato de betametasona, ácido fusídico",
			"valerato de betametasona, hialuronidase",
			"valerato de betametasona, nimesulida",
			"valerato de diflucortolona",
			"valerato de diflucortolona, clorquinaldol",
			"valerato de estradiol",
			"valganciclovir",
			"valproato de sódio",
			"valproato de sódio, ácido valpróico",
			"valsartana",
			"valsartana, hidroclorotiazida",
			"valsartana, sinvastatina",
			"varfarina sódica",
			"verapamil",
			"verteporfina",
			"vigabatrina",
			"vildagliptina",
			"vimpocetina",
			"vincamina",
			"vincristina",
			"vinorelbina",
			"vitelinato de prata",
			"voriconazol",
			"xinafoato de salmeterol",
			"zafirlucaste",
			"zanamivir",
			"zidovudina",
			"zolmitriptana",
			"zopiclona",
			"zuclopentixol"
			};
			
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		requestWindowFeature(Window.FEATURE_NO_TITLE);
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN);
		setContentView(R.layout.list);
		
		final int array_size = array.length;
		
		lv1=(ListView)findViewById(R.id.listView1);
		et1 = (EditText)findViewById(R.id.editText1);
	
	    et1.addTextChangedListener(new TextWatcher(){
	        public void afterTextChanged(Editable s) {
	        	int i;
	        	String s1,s2;
	        	s2=new String(SubstanciasActivity.et1.getText().toString().toLowerCase());
	        	ArrayList<String> lista = new ArrayList<String>();
	        	for (i=0;i<array_size;i++) {
	        		s1=new String(array[i].toLowerCase());	        		
	        	   	if (s1.indexOf(s2)>=0) lista.add(s1);
	        	}	
	        	aa =  new ArrayAdapter<String>(SubstanciasActivity.this,android.R.layout.simple_list_item_1, lista);
	        	lv1=(ListView)findViewById(R.id.listView1);
	            lv1.setAdapter(aa);       	
	        }
	        
			public void beforeTextChanged(CharSequence s, int start, int count, int after){}
	        public void onTextChanged(CharSequence s, int start, int before, int count){}
	    }); 
		
		// By using setAdpater method in listview we an add string array in list.
		lv1.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1 , array));
		lv1.setOnItemClickListener(this);
	}
	
	public void onItemClick(AdapterView<?> parent, View view,
	        int position, long id) {
	      // When clicked, show a toast with the TextView text
			Log.v("Gen", String.valueOf(position));
	    	Intent intent = new Intent(this, MostraSubstancia.class);
	    	intent.putExtra("Subst",((TextView) view).getText());
	    	startActivity(intent);
	}
	
	//Mostra o teclado virtual caso a tecla de procura seja pressionada
	@Override
    public boolean onSearchRequested() {
    	InputMethodManager imm = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
  	  	imm.showSoftInput(getCurrentFocus(), InputMethodManager.SHOW_FORCED);
        return true;
    }
	
	//Cria o menu de opções
	@Override
    public boolean onCreateOptionsMenu(Menu menu){
    	MenuInflater inflater = getMenuInflater();
    	inflater.inflate(R.menu.menu, menu);
    	return true;
    }
	
	@Override
	//Verifica qual opção foi selecionada e executa ação para ela
	public boolean onOptionsItemSelected(MenuItem item){
		//Opção Procurar
    	if(item.getItemId()==R.id.search){
    		//Mostra teclado virtual
    		InputMethodManager imm = (InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);
      	  	imm.showSoftInput(getCurrentFocus(), InputMethodManager.SHOW_FORCED);
    		return true;
    	}
    	//Opção Sobre, mostra o dialog
    	else if(item.getItemId()==R.id.sobre) GenericosActivity.MostraSobre(this);
    	return super.onOptionsItemSelected(item);
    }
}
